# Generated by Django 5.2.4 on 2025-08-07 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krushi_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerdata',
            name='expected_harvest_date',
        ),
        migrations.RemoveField(
            model_name='farmerdata',
            name='sowing_date',
        ),
    ]
