# Generated by Django 5.2.4 on 2025-08-07 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krushi_app', '0002_remove_farmerdata_expected_harvest_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerdata',
            name='fertilizer_used',
        ),
        migrations.RemoveField(
            model_name='farmerdata',
            name='irrigation_type',
        ),
        migrations.RemoveField(
            model_name='farmerdata',
            name='pesticide_used',
        ),
    ]
