# Generated by Django 5.2.4 on 2025-08-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krushi_app', '0005_add_water_irrigation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerdata',
            name='organic_type',
            field=models.CharField(choices=[('Organic', 'Organic'), ('Non-organic', 'Non-organic')], default='Non-organic', max_length=15),
            preserve_default=False,
        ),
    ]
