# Generated by Django 5.2.4 on 2025-08-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krushi_app', '0006_farmerdata_organic_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerdata',
            name='aadhaar_image',
            field=models.ImageField(blank=True, null=True, upload_to='aadhaar_images/'),
        ),
        migrations.AddField(
            model_name='farmerdata',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
