# Generated by Django 5.2.4 on 2025-08-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krushi_app', '0007_farmerdata_aadhaar_image_farmerdata_aadhaar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerdata',
            name='water_source',
            field=models.CharField(choices=[('Canal', 'Canal'), ('Borewell', 'Borewell'), ('Rain-fed', 'Rain-fed'), ('Drip farming', 'Drip farming')], max_length=20),
        ),
    ]
